---
tunnel: ii-nz
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - hostname: cftest.ii.nz
    originRequest:
      originServerName: cftest.ii.nz
    service: http://ii-nz:8080
  - service: http_status:404
