---
version: "2"
services:
  ii-nz:
    build:
      context: .
      dockerfile: ii-nz.Dockerfile
    networks:
      - shared
    ports:
      - "8080:8080"
    restart: always
  cfcfg:
    image: alpine:3.18
    user: 0
    environment:
      - CF_CREDS
    command:
      - sh
      - -c
      - |
        chown -R 65532 /etc/cloudflared/creds
        rm -rfv /etc/cloudflared/creds/credentials.json
        mkdir -p /etc/cloudflared/creds/
        echo "$CF_CREDS" | base64 -d > /etc/cloudflared/creds/credentials.json
        chown -R 65532 /etc/cloudflared/
    volumes:
      - cf:/etc/cloudflared:z
    restart: on-failure
  cloudflared:
    build:
      context: .
      dockerfile: cloudflared.Dockerfile
    command: tunnel --config /usr/etc/cloudflared/config.yaml run
    # user: 0
    networks:
      - shared
    volumes:
      - cf:/etc/cloudflared:ro,z
    restart: always
networks:
  shared: {}
volumes:
  cf: {}
